const data = {
  "Scrawled cowfish": {
    class: "Actinopterygii",
    order: "Tetraodontiformes",
    family: "Ostraciidae",
    genus: "Acanthostracion",
    species: "A. quadricornis",
    imageSrc:
      "//upload.wikimedia.org/wikipedia/commons/thumb/3/33/Scrawledcowfish.jpg/220px-Scrawledcowfish.jpg",
    commonName: "Scrawled cowfish",
  },
  "French angelfish": {
    class: "Actinopterygii",
    order: "Perciformes",
    family: "Pomacanthidae",
    genus: "Pomacanthus",
    species: "P. paru",
    imageSrc:
      "//upload.wikimedia.org/wikipedia/commons/thumb/d/d9/Pomacanthus_paru3.jpg/220px-Pomacanthus_paru3.jpg",
    commonName: "French angelfish",
  },
  "Grey angelfish": undefined,
  "Queen angelfish": {
    class: "Actinopterygii",
    order: "Perciformes",
    family: "Pomacanthidae",
    genus: "Holacanthus",
    species: "H. ciliaris",
    imageSrc:
      "//upload.wikimedia.org/wikipedia/commons/thumb/9/9f/Queen_Angelfish.jpg/220px-Queen_Angelfish.jpg",
    commonName: "Queen angelfish",
  },
  "Queen triggerfish": {
    class: "Actinopterygii",
    order: "Tetraodontiformes",
    family: "Balistidae",
    genus: "Balistes",
    species: "B. vetula",
    imageSrc:
      "//upload.wikimedia.org/wikipedia/commons/thumb/a/ae/4987_aquaimages.jpg/220px-4987_aquaimages.jpg",
    commonName: "Queen triggerfish",
  },
  "Banded butterflyfish": {
    class: "Actinopterygii",
    order: "Perciformes",
    family: "Chaetodontidae",
    genus: "Chaetodon",
    species: "C. striatus",
    imageSrc:
      "//upload.wikimedia.org/wikipedia/commons/thumb/6/65/Chaetodon_striatus_Brasil.jpg/220px-Chaetodon_striatus_Brasil.jpg",
    commonName: "Banded butterflyfish",
  },
  "Foureye butterflyfish": {
    class: "Actinopterygii",
    order: "Perciformes",
    family: "Chaetodontidae",
    genus: "Chaetodon",
    species: "C. capistratus",
    imageSrc:
      "//upload.wikimedia.org/wikipedia/commons/thumb/0/00/Chaetodon_capistratus1.jpg/220px-Chaetodon_capistratus1.jpg",
    commonName: "Foureye butterflyfish",
  },

  "Gray angelfish": {
    class: "Actinopterygii",
    order: "Perciformes",
    family: "Pomacanthidae",
    genus: "Pomacanthus",
    species: "P. arcuatus",
    imageSrc:
      "//upload.wikimedia.org/wikipedia/commons/thumb/d/d1/Pomacanthus_arcuatus_109580400.jpg/220px-Pomacanthus_arcuatus_109580400.jpg",
    commonName: "Gray angelfish",
  },
  "Blue tang": {
    class: undefined,
    order: undefined,
    family: undefined,
    genus: undefined,
    species: undefined,
    imageSrc: undefined,
    commonName: "Blue tang",
  },
  "Ocean surgeonfish": {
    class: undefined,
    order: undefined,
    family: undefined,
    genus: undefined,
    species: undefined,
    imageSrc: undefined,
    commonName: "Ocean surgeonfish",
  },
  "Queen parrotfish": {
    class: "Actinopterygii",
    order: "Labriformes",
    family: "Scaridae",
    genus: "Scarus",
    species: "S. vetula",
    imageSrc:
      "//upload.wikimedia.org/wikipedia/commons/thumb/1/17/Scarus_vetula.jpg/220px-Scarus_vetula.jpg",
    commonName: "Queen parrotfish",
  },
  "Striped parrotfish": undefined,
  "Stoplight parrotfish": {
    class: "Actinopterygii",
    order: "Labriformes",
    family: "Scaridae",
    genus: "Sparisoma",
    species: "S. viride",
    imageSrc:
      "//upload.wikimedia.org/wikipedia/commons/thumb/f/f3/Stoplight-parrotfish.jpg/220px-Stoplight-parrotfish.jpg",
    commonName: "Stoplight parrotfish",
  },
  "Princess parrotfish": {
    class: "Actinopterygii",
    order: "Labriformes",
    family: "Scaridae",
    genus: "Scarus",
    species: "S. taeniopterus",
    imageSrc:
      "//upload.wikimedia.org/wikipedia/commons/thumb/c/cb/Princess-parrotfish.png/220px-Princess-parrotfish.png",
    commonName: "Princess parrotfish",
  },
  "Tiger grouper": {
    class: "Actinopterygii",
    order: "Perciformes",
    family: "Serranidae",
    genus: "Mycteroperca",
    species: "M. tigris",
    imageSrc:
      "//upload.wikimedia.org/wikipedia/commons/thumb/1/10/Tiger_grouper.JPG/220px-Tiger_grouper.JPG",
    commonName: "Tiger grouper",
  },
  Coney: {
    class: undefined,
    order: undefined,
    family: undefined,
    genus: undefined,
    species: undefined,
    imageSrc: undefined,
    commonName: "Coney",
  },
  "French grunt": {
    class: "Actinopterygii",
    order: "Perciformes",
    family: "Haemulidae",
    genus: "Haemulon",
    species: "H. flavolineatum",
    imageSrc:
      "//upload.wikimedia.org/wikipedia/commons/thumb/3/3d/Haemulon_flavolineatum_French_grunt.jpg/220px-Haemulon_flavolineatum_French_grunt.jpg",
    commonName: "French grunt",
  },
  "Smallmouth grunt": undefined,
  "Bluestriped grunt": {
    class: "Actinopterygii",
    order: "Perciformes",
    family: "Haemulidae",
    genus: "Haemulon",
    species: "H. sciurus",
    imageSrc:
      "//upload.wikimedia.org/wikipedia/commons/thumb/5/54/Blue_Stripe_Grunt._Haemulon_sciurus.jpg/220px-Blue_Stripe_Grunt._Haemulon_sciurus.jpg",
    commonName: "Bluestriped grunt",
  },
  "Black margate": {
    class: "Actinopterygii",
    order: "Perciformes",
    family: "Haemulidae",
    genus: "Anisotremus",
    species: "A. surinamensis",
    imageSrc:
      "//upload.wikimedia.org/wikipedia/commons/thumb/a/a6/Anisotremus_surinamensis_1438594.jpg/220px-Anisotremus_surinamensis_1438594.jpg",
    commonName: "Black margate",
  },
  "Schoolmaster snapper": {
    class: "Actinopterygii",
    order: "Perciformes",
    family: "Lutjanidae",
    genus: "Lutjanus",
    species: "L. apodus",
    imageSrc:
      "//upload.wikimedia.org/wikipedia/commons/thumb/e/e8/Lutjanus.JPG/220px-Lutjanus.JPG",
    commonName: "Schoolmaster snapper",
  },
  "Yellowtail snapper": {
    class: "Actinopterygii",
    order: "Perciformes",
    family: "Lutjanidae",
    genus: "OcyurusT. N. Gill, 1862",
    species: "O. chrysurus",
    imageSrc:
      "//upload.wikimedia.org/wikipedia/commons/thumb/f/fe/Yellowtail_snapper_seen_from_Underwater_Tunnel_Atlantis.jpg/220px-Yellowtail_snapper_seen_from_Underwater_Tunnel_Atlantis.jpg",
    commonName: "Yellowtail snapper",
  },
  "Black durgon": {
    class: "Actinopterygii",
    order: "Tetraodontiformes",
    family: "Balistidae",
    genus: "Melichthys",
    species: "M. niger",
    imageSrc:
      "//upload.wikimedia.org/wikipedia/commons/thumb/3/33/Black_durgon_Melichthys_niger_%282414051345%29.jpg/220px-Black_durgon_Melichthys_niger_%282414051345%29.jpg",
    commonName: "Black durgon",
  },
  "Whitespotted filefish": {
    class: undefined,
    order: undefined,
    family: undefined,
    genus: undefined,
    species: undefined,
    imageSrc: undefined,
    commonName: "Whitespotted filefish",
  },
  Hogfish: {
    class: "Actinopterygii",
    order: "Labriformes",
    family: "Labridae",
    genus: "LachnolaimusG. Cuvier, 1829",
    species: "L. maximus",
    imageSrc:
      "//upload.wikimedia.org/wikipedia/commons/thumb/6/62/Hogfish.JPG/220px-Hogfish.JPG",
    commonName: "Hogfish",
  },
  "Spanish hogfish": {
    class: "Actinopterygii",
    order: "Labriformes",
    family: "Labridae",
    genus: "Bodianus",
    species: "B. rufus",
    imageSrc:
      "//upload.wikimedia.org/wikipedia/commons/thumb/6/65/Bodianus_rufus%2C_Adult_%28Spanish_Hogfish%29.jpg/220px-Bodianus_rufus%2C_Adult_%28Spanish_Hogfish%29.jpg",
    commonName: "Spanish hogfish",
  },

  "Green sea turtle": {
    commonName: "Green sea turtle",
    phylum: "Chordata",
    class: "Reptilia",
    order: "Testudines",
    family: "Cheloniidae",
    genus: "CheloniaBrongniart, 1800",
    species: "C. mydas",
    imageSrc:
      "//upload.wikimedia.org/wikipedia/commons/thumb/e/e5/Green_turtle_swimming_over_coral_reefs_in_Kona.jpg/220px-Green_turtle_swimming_over_coral_reefs_in_Kona.jpg",
  },
  "Hawksbill sea turtle": {
    commonName: "Hawksbill sea turtle",
    phylum: "Chordata",
    class: "Reptilia",
    order: "Testudines",
    family: "Cheloniidae",
    genus: "EretmochelysFitzinger, 1843",
    species: "E. imbricata",
    imageSrc:
      "//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Eretmochelys-imbricata-K%C3%A9lonia-2.JPG/220px-Eretmochelys-imbricata-K%C3%A9lonia-2.JPG",
  },
  Bluehead: {
    commonName: "Bluehead",
    phylum: "Chordata",
    class: "Actinopterygii",
    order: "Labriformes",
    family: "Labridae",
    genus: "Thalassoma",
    species: "T. amblycephalum",
    imageSrc:
      "//upload.wikimedia.org/wikipedia/commons/thumb/4/40/KogashiraBRnup.jpg/220px-KogashiraBRnup.jpg",
  },
  "Yellowhead wrasse": {
    commonName: "Yellowhead wrasse",
    phylum: "Chordata",
    class: "Actinopterygii",
    order: "Labriformes",
    family: "Labridae",
    genus: "Halichoeres",
    species: "H. garnoti",
    imageSrc:
      "//upload.wikimedia.org/wikipedia/commons/thumb/2/25/Reef1538_-_Flickr_-_NOAA_Photo_Library.jpg/220px-Reef1538_-_Flickr_-_NOAA_Photo_Library.jpg",
  },
  "Clown wrasse": {
    commonName: "Clown wrasse",
    phylum: undefined,
    class: undefined,
    order: undefined,
    family: undefined,
    genus: undefined,
    species: undefined,
    imageSrc: undefined,
  },
  "Rainbow wrasse": {
    commonName: "Rainbow wrasse",
    phylum: "Chordata",
    class: "Actinopterygii",
    order: "Labriformes",
    family: "Labridae",
    genus: "CorisLacépède, 1801",
    species: "",
    imageSrc:
      "//upload.wikimedia.org/wikipedia/commons/thumb/e/eb/Coris_gaimard_real.jpg/220px-Coris_gaimard_real.jpg",
  },
  "Yellowcheek wrasse": {
    commonName: "Yellowcheek wrasse",
    phylum: "Chordata",
    class: "Actinopterygii",
    order: "Labriformes",
    family: "Labridae",
    genus: "Halichoeres",
    species: "H. cyanocephalus",
    imageSrc:
      "//upload.wikimedia.org/wikipedia/commons/thumb/9/9c/Halichoeres_cyanocephalus.jpg/220px-Halichoeres_cyanocephalus.jpg",
  },
  "Greenband wrasse": undefined,
  "Painted wrasse": undefined,
  "Midnight parrotfish": {
    commonName: "Midnight parrotfish",
    phylum: "Chordata",
    class: "Actinopterygii",
    order: "Labriformes",
    family: "Scaridae",
    genus: "Scarus",
    species: "S. coelestinus",
    imageSrc:
      "//upload.wikimedia.org/wikipedia/commons/thumb/3/3c/Midnight-parrotfish.png/220px-Midnight-parrotfish.png",
  },
  "Blue parrotfish": {
    commonName: "Blue parrotfish",
    phylum: "Chordata",
    class: "Actinopterygii",
    order: "Labriformes",
    family: "Scaridae",
    genus: "Scarus",
    species: "S. coeruleus",
    imageSrc:
      "//upload.wikimedia.org/wikipedia/commons/thumb/b/b2/Scarus_coeruleus_in_Madagascar_Reef.jpg/220px-Scarus_coeruleus_in_Madagascar_Reef.jpg",
  },
  "Rainbow parrotfish": {
    commonName: "Rainbow parrotfish",
    phylum: "Chordata",
    class: "Actinopterygii",
    order: "Labriformes",
    family: "Scaridae",
    genus: "Scarus",
    species: "S. guacamaia",
    imageSrc:
      "//upload.wikimedia.org/wikipedia/commons/thumb/f/f7/Rainbow_parrotfish.jpg/220px-Rainbow_parrotfish.jpg",
  },
  "Redtail parrotfish": {
    commonName: "Redtail parrotfish",
    phylum: "Chordata",
    class: "Actinopterygii",
    order: "Labriformes",
    family: "Scaridae",
    genus: "Sparisoma",
    species: "S. chrysopterum",
    imageSrc:
      "//upload.wikimedia.org/wikipedia/commons/thumb/5/51/Sparisoma_chrysopterum_-_pone.0010676.g135.png/220px-Sparisoma_chrysopterum_-_pone.0010676.g135.png",
  },
  "Yellowhead jawfish": {
    commonName: "Yellowhead jawfish",
    phylum: "Chordata",
    class: "Actinopterygii",
    order: "",
    family: "Opistognathidae",
    genus: "Opistognathus",
    species: "O. aurifrons",
    imageSrc:
      "//upload.wikimedia.org/wikipedia/commons/thumb/d/d5/Opistognathus_aurifrons.jpg/220px-Opistognathus_aurifrons.jpg",
  },
  "Banded jawfish": undefined,
  "Great barracuda": {
    commonName: "Great barracuda",
    phylum: "Chordata",
    class: "Actinopterygii",
    order: "Istiophoriformes",
    family: "Sphyraenidae",
    genus: "Sphyraena",
    species: "S. barracuda",
    imageSrc:
      "//upload.wikimedia.org/wikipedia/commons/thumb/e/eb/Barracuda_laban.jpg/220px-Barracuda_laban.jpg",
  },
  "Palehead blenny": {
    commonName: "Palehead blenny",
    phylum: "Chordata",
    class: "Actinopterygii",
    order: "Blenniiformes",
    family: "Labrisomidae",
    genus: "Gobioclinus",
    species: "G. gobio",
    imageSrc:
      "//upload.wikimedia.org/wikipedia/commons/thumb/9/9d/Labrisomus_gobio_-_pone.0010676.g145.png/220px-Labrisomus_gobio_-_pone.0010676.g145.png",
  },
  "Blue gobi": undefined,
  "Yellowtail damselfish": {
    commonName: "Yellowtail damselfish",
    phylum: "Chordata",
    class: "Actinopterygii",
    order: "",
    family: "Pomacentridae",
    genus: "Microspathodon",
    species: "M. chrysurus",
    imageSrc:
      "//upload.wikimedia.org/wikipedia/commons/thumb/c/c7/Yellotaildamsel.jpg/220px-Yellotaildamsel.jpg",
  },
  Surgeonfish: {
    commonName: "Surgeonfish",
    phylum: "Chordata",
    class: "Actinopterygii",
    order: "Acanthuriformes",
    family: "AcanthuridaeBonaparte, 1835[1]",
    genus: "",
    species: "",
    imageSrc:
      "//upload.wikimedia.org/wikipedia/commons/thumb/f/f6/Acanthurussohal-ArabischerDoktor.jpg/220px-Acanthurussohal-ArabischerDoktor.jpg",
  },
  "Blue chromis": {
    commonName: "Blue chromis",
    phylum: "Chordata",
    class: "Actinopterygii",
    order: "",
    family: "Pomacentridae",
    genus: "Chromis",
    species: "C. cyanea",
    imageSrc:
      "//upload.wikimedia.org/wikipedia/commons/thumb/e/e4/Chromis_cyanea_Gratwicke.jpg/220px-Chromis_cyanea_Gratwicke.jpg",
  },
  "Rock beauty": {
    commonName: "Rock beauty",
    phylum: "Chordata",
    class: "Actinopterygii",
    order: "Perciformes",
    family: "Pomacanthidae",
    genus: "Holacanthus",
    species: "H. tricolor",
    imageSrc:
      "//upload.wikimedia.org/wikipedia/commons/thumb/a/a2/Holacanthus_tricolor_1.jpg/220px-Holacanthus_tricolor_1.jpg",
  },
  "Blue angelfish": {
    commonName: "Blue angelfish",
    phylum: "Chordata",
    class: "Actinopterygii",
    order: "Perciformes",
    family: "Pomacanthidae",
    genus: "Holacanthus",
    species: "H. bermudensis",
    imageSrc:
      "//upload.wikimedia.org/wikipedia/commons/thumb/a/a0/Blue_Angelfish_JG.jpg/220px-Blue_Angelfish_JG.jpg",
  },
  "Reef butterflyfish": {
    commonName: "Reef butterflyfish",
    phylum: "Chordata",
    class: "Actinopterygii",
    order: "Perciformes",
    family: "Chaetodontidae",
    genus: "Chaetodon",
    species: "C. sedentarius",
    imageSrc:
      "//upload.wikimedia.org/wikipedia/commons/thumb/9/9a/Chaetodon_sedentarius_Brasil.jpg/220px-Chaetodon_sedentarius_Brasil.jpg",
  },
  "Threeband butterflyfish": undefined,
  "Spotted drum": {
    commonName: "Spotted drum",
    phylum: "Chordata",
    class: "Actinopterygii",
    order: "Acanthuriformes",
    family: "Sciaenidae",
    genus: "Eques",
    species: "E. punctatus",
    imageSrc:
      "//upload.wikimedia.org/wikipedia/commons/thumb/e/ee/Spotted-drum.png/220px-Spotted-drum.png",
  },
  "White grunt": {
    commonName: "White grunt",
    phylum: "Chordata",
    class: "Actinopterygii",
    order: "Perciformes",
    family: "Haemulidae",
    genus: "Haemulon",
    species: "H. plumierii",
    imageSrc:
      "//upload.wikimedia.org/wikipedia/commons/thumb/5/58/White_Grunt_%285658507044%29.jpg/220px-White_Grunt_%285658507044%29.jpg",
  },
  Sheepshead: {
    commonName: "Sheepshead",
    phylum: undefined,
    class: undefined,
    order: undefined,
    family: undefined,
    genus: undefined,
    species: undefined,
    imageSrc: undefined,
  },
  "Mutton snapper": {
    commonName: "Mutton snapper",
    phylum: "Chordata",
    class: "Actinopterygii",
    order: "Perciformes",
    family: "Lutjanidae",
    genus: "Lutjanus",
    species: "L. analis",
    imageSrc:
      "//upload.wikimedia.org/wikipedia/commons/thumb/1/1d/Lutjanus_analis_SI.jpg/220px-Lutjanus_analis_SI.jpg",
  },
  "Yellowtail snapper": {
    commonName: "Yellowtail snapper",
    phylum: "Chordata",
    class: "Actinopterygii",
    order: "Perciformes",
    family: "Lutjanidae",
    genus: "OcyurusT. N. Gill, 1862",
    species: "O. chrysurus",
    imageSrc:
      "//upload.wikimedia.org/wikipedia/commons/thumb/f/fe/Yellowtail_snapper_seen_from_Underwater_Tunnel_Atlantis.jpg/220px-Yellowtail_snapper_seen_from_Underwater_Tunnel_Atlantis.jpg",
  },
  "Bar Jack": {
    commonName: "Bar Jack",
    phylum: "Chordata",
    class: "Actinopterygii",
    order: "Carangiformes",
    family: "Carangidae",
    genus: "Caranx",
    species: "C. ruber",
    imageSrc:
      "//upload.wikimedia.org/wikipedia/commons/thumb/2/23/Bar_jack_portrait.jpg/220px-Bar_jack_portrait.jpg",
  },
  Palometa: {
    commonName: "Palometa",
    phylum: undefined,
    class: undefined,
    order: undefined,
    family: undefined,
    genus: undefined,
    species: undefined,
    imageSrc: undefined,
  },
  "Bigeye scad": {
    commonName: "Bigeye scad",
    phylum: "Chordata",
    class: "Actinopterygii",
    order: "Carangiformes",
    family: "Carangidae",
    genus: "Selar",
    species: "S. crumenophthalmus",
    imageSrc:
      "//upload.wikimedia.org/wikipedia/commons/thumb/4/4d/Fish4443_-_Flickr_-_NOAA_Photo_Library.jpg/220px-Fish4443_-_Flickr_-_NOAA_Photo_Library.jpg",
  },
  "Glasseye snapper": {
    commonName: "Glasseye snapper",
    phylum: "Chordata",
    class: "Actinopterygii",
    order: "Perciformes",
    family: "Priacanthidae",
    genus: "HeteropriacanthusFitch & Crooke, 1984",
    species: "H. cruentatus",
    imageSrc:
      "//upload.wikimedia.org/wikipedia/commons/thumb/7/70/Priacanthus_cruentatus.jpg/220px-Priacanthus_cruentatus.jpg",
  },
  "Pale cardinalfish": undefined,
  "Fairy basslet": {
    commonName: "Fairy basslet",
    phylum: "Chordata",
    class: "Actinopterygii",
    order: "Perciformes",
    family: "SerranidaeSwainson, 1839[1]",
    genus: "",
    species: "",
    imageSrc:
      "//upload.wikimedia.org/wikipedia/commons/thumb/c/c8/Cromileptes_altivelis_-_Paddelbarsch_-_Panther_grouper.jpg/220px-Cromileptes_altivelis_-_Paddelbarsch_-_Panther_grouper.jpg",
  },
  "Blackcap basslet": {
    commonName: "Blackcap basslet",
    phylum: "Chordata",
    class: "Actinopterygii",
    order: "",
    family: "Grammatidae",
    genus: "Gramma",
    species: "G. melacara",
    imageSrc:
      "//upload.wikimedia.org/wikipedia/commons/thumb/0/07/Black_Cap_Basslet.jpg/220px-Black_Cap_Basslet.jpg",
  },
  "Mutton hamlet": {
    commonName: "Mutton hamlet",
    phylum: "Chordata",
    class: "Actinopterygii",
    order: "Perciformes",
    family: "Serranidae",
    genus: "Dermatolepis",
    species: "D. inermis",
    imageSrc:
      "//upload.wikimedia.org/wikipedia/commons/thumb/b/b7/Sanc0498_-_Flickr_-_NOAA_Photo_Library.jpg/220px-Sanc0498_-_Flickr_-_NOAA_Photo_Library.jpg",
  },
  "Black grouper": {
    commonName: "Black grouper",
    phylum: "Chordata",
    class: "Actinopterygii",
    order: "Perciformes",
    family: "Serranidae",
    genus: "Mycteroperca",
    species: "M. bonaci",
    imageSrc:
      "//upload.wikimedia.org/wikipedia/commons/thumb/1/1f/Black_grouper2.jpg/220px-Black_grouper2.jpg",
  },
  "Reef bass": undefined,
  "Sand perch": {
    commonName: "Sand perch",
    phylum: "Chordata",
    class: "Actinopterygii",
    order: "Trachiniformes",
    family: "PinguipedidaeGünther, 1860",
    genus: "",
    species: "",
    imageSrc:
      "//upload.wikimedia.org/wikipedia/commons/thumb/5/53/Parapercis_hexophtalma_1.jpg/220px-Parapercis_hexophtalma_1.jpg",
  },
  "Nassau grouper": {
    commonName: "Nassau grouper",
    phylum: "Chordata",
    class: "Actinopterygii",
    order: "Perciformes",
    family: "Serranidae",
    genus: "Epinephelus",
    species: "E. striatus",
    imageSrc:
      "//upload.wikimedia.org/wikipedia/commons/thumb/8/8e/2017%2C_cuba%2C_jardines_aggressor%2C_los_indios%2C_nassau_grouper_maw_%2836883128693%29.jpg/220px-2017%2C_cuba%2C_jardines_aggressor%2C_los_indios%2C_nassau_grouper_maw_%2836883128693%29.jpg",
  },
  "Lined seahorse": {
    commonName: "Lined seahorse",
    phylum: "Chordata",
    class: "Actinopterygii",
    order: "Syngnathiformes",
    family: "Syngnathidae",
    genus: "Hippocampus",
    species: "H. erectus",
    imageSrc:
      "//upload.wikimedia.org/wikipedia/commons/thumb/b/bf/Lined_Seahorse-_Hippocampus_erectus_%286042886100%29.jpg/220px-Lined_Seahorse-_Hippocampus_erectus_%286042886100%29.jpg",
  },
  "Spotted scorpionfish": {
    commonName: "Spotted scorpionfish",
    phylum: "Chordata",
    class: "Actinopterygii",
    order: "Scorpaeniformes",
    family: "Scorpaenidae",
    genus: "Scorpaena",
    species: "S. guttata",
    imageSrc:
      "//upload.wikimedia.org/wikipedia/commons/thumb/c/c4/Scorpaena_guttata.jpg/220px-Scorpaena_guttata.jpg",
  },
  "Reef scorpionfish": undefined,
  Lionfish: {
    commonName: "Lionfish",
    phylum: "Chordata",
    class: "Actinopterygii",
    order: "Scorpaeniformes",
    family: "Scorpaenidae",
    genus: "PteroisOken, 1817[1]",
    species: "",
    imageSrc:
      "//upload.wikimedia.org/wikipedia/commons/thumb/3/3d/Red_lionfish_near_Gilli_Banta_Island.JPG/220px-Red_lionfish_near_Gilli_Banta_Island.JPG",
  },
  "Reef squirrelfish": {
    commonName: "Reef squirrelfish",
    phylum: "Chordata",
    class: "Actinopterygii",
    order: "Holocentriformes",
    family: "Holocentridae",
    genus: "Sargocentron",
    species: "S. coruscum",
    imageSrc:
      "//upload.wikimedia.org/wikipedia/commons/thumb/e/e6/Sargocentron_coruscum_-_pone.0010676.g039.png/220px-Sargocentron_coruscum_-_pone.0010676.g039.png",
  },
  "Coral toadfish": {
    commonName: "Coral toadfish",
    phylum: "Chordata",
    class: "Actinopterygii",
    order: "Batrachoidiformes",
    family: "Batrachoididae",
    genus: "Sanopus",
    species: "S. splendidus",
    imageSrc:
      "//upload.wikimedia.org/wikipedia/commons/thumb/2/2c/Splendidtoadfish_laban.jpg/220px-Splendidtoadfish_laban.jpg",
  },
  "Dwarf frogfish": {
    commonName: "Dwarf frogfish",
    phylum: "Chordata",
    class: "Actinopterygii",
    order: "Lophiiformes",
    family: "Antennariidae",
    genus: "Antennarius",
    species: "A. pauciradiatus",
    imageSrc:
      "//upload.wikimedia.org/wikipedia/commons/thumb/5/56/Antennarius_pauciradiatus_-_pone.0010676.g028.png/220px-Antennarius_pauciradiatus_-_pone.0010676.g028.png",
  },
  Tarpon: {
    commonName: "Tarpon",
    phylum: "Chordata",
    class: "Actinopterygii",
    order: "Elopiformes",
    family: "MegalopidaeD. S. Jordan, 1923",
    genus: "MegalopsValenciennes, 1847",
    species: "",
    imageSrc:
      "//upload.wikimedia.org/wikipedia/commons/thumb/7/7e/Atlantic_tarpon.jpg/220px-Atlantic_tarpon.jpg",
  },
  "Green moray eel": {
    commonName: "Green moray eel",
    phylum: "Chordata",
    class: "Actinopterygii",
    order: "Anguilliformes",
    family: "Muraenidae",
    genus: "Gymnothorax",
    species: "G. funebris",
    imageSrc:
      "//upload.wikimedia.org/wikipedia/commons/thumb/3/33/GreenMorayEel.JPG/220px-GreenMorayEel.JPG",
  },
  "Spotted moray eel": {
    commonName: "Spotted moray eel",
    phylum: "Chordata",
    class: "Actinopterygii",
    order: "Anguilliformes",
    family: "Muraenidae",
    genus: "Gymnothorax",
    species: "G. isingteena",
    imageSrc:
      "//upload.wikimedia.org/wikipedia/commons/thumb/7/74/Gymnothorax_isingteena.jpg/220px-Gymnothorax_isingteena.jpg",
  },
  "Purplemouth moral eel": undefined,
  "Goldentail moral eey": undefined,
  "Spotted eagle ray": {
    commonName: "Spotted eagle ray",
    phylum: "Chordata",
    class: "Chondrichthyes",
    order: "Myliobatiformes",
    family: "Aetobatidae",
    genus: "Aetobatus",
    species: "A. narinari",
    imageSrc:
      "//upload.wikimedia.org/wikipedia/commons/thumb/a/ad/Eagle_Ray_Turks_and_Caicos_Dec_15_2006.JPG/220px-Eagle_Ray_Turks_and_Caicos_Dec_15_2006.JPG",
  },
  "Southern stingray": {
    commonName: "Southern stingray",
    phylum: "Chordata",
    class: "Chondrichthyes",
    order: "Myliobatiformes",
    family: "Dasyatidae",
    genus: "Hypanus",
    species: "H. americanus",
    imageSrc:
      "//upload.wikimedia.org/wikipedia/commons/thumb/2/29/Dasyatis_americana_SI.jpg/220px-Dasyatis_americana_SI.jpg",
  },
  "Yellow stingray": {
    commonName: "Yellow stingray",
    phylum: "Chordata",
    class: "Chondrichthyes",
    order: "Myliobatiformes",
    family: "Urotrygonidae",
    genus: "Urobatis",
    species: "U. jamaicensis",
    imageSrc:
      "//upload.wikimedia.org/wikipedia/commons/thumb/5/53/Yellow_Stingray%2C_Belize%2C_2007-09.jpg/220px-Yellow_Stingray%2C_Belize%2C_2007-09.jpg",
  },
  "Lesser electric ray": {
    commonName: "Lesser electric ray",
    phylum: "Chordata",
    class: "Chondrichthyes",
    order: "Torpediniformes",
    family: "Narcinidae",
    genus: "Narcine",
    species: "N. bancroftii",
    imageSrc:
      "//upload.wikimedia.org/wikipedia/commons/thumb/b/b7/Fish4345_-_Flickr_-_NOAA_Photo_Library.jpg/220px-Fish4345_-_Flickr_-_NOAA_Photo_Library.jpg",
  },
  Guitarfish: {
    commonName: "Guitarfish",
    phylum: "Chordata",
    class: "Chondrichthyes",
    order: "Rhinopristiformes",
    family: "RhinobatidaeJ. P. Müller & Henle, 1837",
    genus: "",
    species: "",
    imageSrc:
      "//upload.wikimedia.org/wikipedia/commons/thumb/f/fa/Shovelnose_guitarfish.JPG/220px-Shovelnose_guitarfish.JPG",
  },
  "Manta ray": {
    commonName: "Manta ray",
    phylum: "Chordata",
    class: "Chondrichthyes",
    order: "Myliobatiformes",
    family: "Mobulidae",
    genus: "MantaBancroft, 1829[2]",
    species: "",
    imageSrc:
      "//upload.wikimedia.org/wikipedia/commons/thumb/3/30/Dharavandhoo_Thila_-_Manata_Black_Pearl.JPG/220px-Dharavandhoo_Thila_-_Manata_Black_Pearl.JPG",
  },
  "Nurse shark": {
    commonName: "Nurse shark",
    phylum: "Chordata",
    class: "Chondrichthyes",
    order: "Orectolobiformes",
    family: "Ginglymostomatidae",
    genus: "Ginglymostoma",
    species: "G. cirratum",
    imageSrc:
      "//upload.wikimedia.org/wikipedia/commons/thumb/d/d1/Nurse_shark.jpg/220px-Nurse_shark.jpg",
  },
  "Whitespotted puffer": undefined,
  "Spotted trunkfish": {
    commonName: "Spotted trunkfish",
    phylum: "Chordata",
    class: "Actinopterygii",
    order: "Tetraodontiformes",
    family: "Ostraciidae",
    genus: "Lactophrys",
    species: "L. bicaudalis",
    imageSrc:
      "//upload.wikimedia.org/wikipedia/commons/thumb/f/fb/Spotted_Trunkfish.jpg/220px-Spotted_Trunkfish.jpg",
  },
  "Yellow boxfish": {
    commonName: "Yellow boxfish",
    phylum: "Chordata",
    class: "Actinopterygii",
    order: "Tetraodontiformes",
    family: "Ostraciidae",
    genus: "Ostracion",
    species: "O. cubicum",
    imageSrc:
      "//upload.wikimedia.org/wikipedia/commons/thumb/7/79/Kofferfisch_%28Ostracion_cubicus%29_02.jpg/220px-Kofferfisch_%28Ostracion_cubicus%29_02.jpg",
  },
  "Whitespotted pygmy filefish": {
    commonName: "Whitespotted pygmy filefish",
    phylum: "Chordata",
    class: "Actinopterygii",
    order: "Tetraodontiformes",
    family: "Monacanthidae",
    genus: "Rudarius",
    species: "R. ercodes",
    imageSrc:
      "//upload.wikimedia.org/wikipedia/commons/thumb/d/d8/AmimeHGoya.jpg/220px-AmimeHGoya.jpg",
  },
  "Broom filefish": {
    commonName: "Broom filefish",
    phylum: "Chordata",
    class: "Actinopterygii",
    order: "Tetraodontiformes",
    family: "Monacanthidae",
    genus: "AmansesJ. E. Gray, 1835",
    species: "A. scopas",
    imageSrc:
      "//upload.wikimedia.org/wikipedia/commons/thumb/1/1e/Amanses_scopas.jpg/220px-Amanses_scopas.jpg",
  },
  "Peacock flounder": {
    commonName: "Peacock flounder",
    phylum: "Chordata",
    class: "Actinopterygii",
    order: "Pleuronectiformes",
    family: "Bothidae",
    genus: "Bothus",
    species: "B. mancus",
    imageSrc:
      "//upload.wikimedia.org/wikipedia/commons/thumb/9/96/Bothidae_-_Bothus_mancus.jpg/220px-Bothidae_-_Bothus_mancus.jpg",
  },
  "Black durgon": {
    commonName: "Black durgon",
    phylum: "Chordata",
    class: "Actinopterygii",
    order: "Tetraodontiformes",
    family: "Balistidae",
    genus: "Melichthys",
    species: "M. niger",
    imageSrc:
      "//upload.wikimedia.org/wikipedia/commons/thumb/3/33/Black_durgon_Melichthys_niger_%282414051345%29.jpg/220px-Black_durgon_Melichthys_niger_%282414051345%29.jpg",
  },
  "Halichoeres maculipinna": {
    commonName: "Halichoeres maculipinna",
    phylum: "Chordata",
    class: "Actinopterygii",
    order: "Labriformes",
    family: "Labridae",
    genus: "Halichoeres",
    species: "H. maculipinna",
    imageSrc:
      "//upload.wikimedia.org/wikipedia/commons/thumb/5/5c/Halichoeres_maculipinna.jpg/220px-Halichoeres_maculipinna.jpg",
  },
  "Archosargus probatocephalus": {
    commonName: "Archosargus probatocephalus",
    phylum: "Chordata",
    class: "Actinopterygii",
    order: "Spariformes",
    family: "Sparidae",
    genus: "Archosargus",
    species: "A. probatocephalus",
    imageSrc:
      "//upload.wikimedia.org/wikipedia/commons/thumb/6/66/Sheepshead.jpg/220px-Sheepshead.jpg",
  },
  "Haemulon chrysargyreum": {
    commonName: "Haemulon chrysargyreum",
    phylum: "Chordata",
    class: "Actinopterygii",
    order: "Perciformes",
    family: "Haemulidae",
    genus: "Haemulon",
    species: "H. chrysargyreum",
    imageSrc:
      "//upload.wikimedia.org/wikipedia/commons/thumb/2/23/Haemulon_chrysargyreum.JPG/220px-Haemulon_chrysargyreum.JPG",
  },
  "Cantherhines macrocerus": {
    commonName: "Cantherhines macrocerus",
    phylum: "Chordata",
    class: "Actinopterygii",
    order: "Tetraodontiformes",
    family: "Monacanthidae",
    genus: "Cantherhines",
    species: "C. macrocerus",
    imageSrc:
      "//upload.wikimedia.org/wikipedia/commons/thumb/d/da/American_whitespotted_filefish.jpg/220px-American_whitespotted_filefish.jpg",
  },
  "Slippery dick": {
    commonName: "Slippery dick",
    phylum: "Chordata",
    class: "Actinopterygii",
    order: "Labriformes",
    family: "Labridae",
    genus: "Halichoeres",
    species: "H. bivittatus",
    imageSrc:
      "//upload.wikimedia.org/wikipedia/commons/thumb/6/6e/Slippery_Dick_Wrasse_-_Halichoeres_bivittatus.jpg/220px-Slippery_Dick_Wrasse_-_Halichoeres_bivittatus.jpg",
  },
  "Three-banded butterflyfish": {
    commonName: "Three-banded butterflyfish",
    phylum: "Chordata",
    class: "Actinopterygii",
    order: "Perciformes",
    family: "Chaetodontidae",
    genus: "Chaetodon",
    species: "C. robustus",
    imageSrc:
      "//upload.wikimedia.org/wikipedia/commons/thumb/0/03/Chaetodon_robustus_137847685.jpg/220px-Chaetodon_robustus_137847685.jpg",
  },
  "Purplemouth moray eel": {
    commonName: "Purplemouth moray eel",
    phylum: "Chordata",
    class: "Actinopterygii",
    order: "Anguilliformes",
    family: "Muraenidae",
    genus: "Gymnothorax",
    species: "G. vicinus",
    imageSrc:
      "//upload.wikimedia.org/wikipedia/commons/thumb/1/15/Gymnothorax_vicinus_-_pone.0010676.g011.png/220px-Gymnothorax_vicinus_-_pone.0010676.g011.png",
  },
  "Gymnothorax miliaris": {
    commonName: "Gymnothorax miliaris",
    phylum: "Chordata",
    class: "Actinopterygii",
    order: "Anguilliformes",
    family: "Muraenidae",
    genus: "Gymnothorax",
    species: "G. miliaris",
    imageSrc:
      "//upload.wikimedia.org/wikipedia/commons/thumb/6/67/Gymnothorax_miliaris_%28goldentail_moray_eel%29_%28San_Salvador_Island%2C_Bahamas%29_3_%2816171148365%29.jpg/220px-Gymnothorax_miliaris_%28goldentail_moray_eel%29_%28San_Salvador_Island%2C_Bahamas%29_3_%2816171148365%29.jpg",
  },
  "White-spotted puffer": {
    commonName: "White-spotted puffer",
    phylum: "Chordata",
    class: "Actinopterygii",
    order: "Tetraodontiformes",
    family: "Tetraodontidae",
    genus: "Arothron",
    species: "A. hispidus",
    imageSrc:
      "//upload.wikimedia.org/wikipedia/commons/thumb/c/cc/Whitespotted_puffer.JPG/220px-Whitespotted_puffer.JPG",
  },
  Porcupinefish: {
    commonName: "Porcupinefish",
    phylum: "Chordata",
    class: "Actinopterygii",
    order: "Tetraodontiformes",
    family: "DiodontidaeBonaparte, 1838",
    genus: "",
    species: "",
    imageSrc:
      "//upload.wikimedia.org/wikipedia/commons/thumb/d/d1/Diodon_nicthemerus.jpg/220px-Diodon_nicthemerus.jpg",
  },
  "Whitetip reef shark": {
    commonName: "Whitetip reef shark",
    phylum: "Chordata",
    class: "Chondrichthyes",
    order: "Carcharhiniformes",
    family: "Carcharhinidae",
    genus: "TriaenodonJ. P. Müller & Henle, 1837",
    species: "T. obesus",
    imageSrc:
      "//upload.wikimedia.org/wikipedia/commons/thumb/9/95/Carcharhinus_albimarginatus-shark.jpg/220px-Carcharhinus_albimarginatus-shark.jpg",
  },
  "Sergeant major (fish)": {
    commonName: "Sergeant major (fish)",
    phylum: "Chordata",
    class: "Actinopterygii",
    order: "",
    family: "Pomacentridae",
    genus: "Abudefduf",
    species: "A. saxatilis",
    imageSrc:
      "//upload.wikimedia.org/wikipedia/commons/thumb/c/cd/SergeantMajor_Icon.jpg/220px-SergeantMajor_Icon.jpg",
  },
  "Stenorhynchus seticornis": {
    commonName: "Stenorhynchus seticornis",
    phylum: "Arthropoda",
    class: "Malacostraca",
    order: "Decapoda",
    family: "Inachidae",
    genus: "Stenorhynchus",
    species: "S. seticornis",
    imageSrc:
      "//upload.wikimedia.org/wikipedia/commons/thumb/8/8a/Stenorhynchus_seticornis.jpg/220px-Stenorhynchus_seticornis.jpg",
  },
  "Maguimithrax spinosissimus": {
    commonName: "Maguimithrax spinosissimus",
    phylum: "Arthropoda",
    class: "Malacostraca",
    order: "Decapoda",
    family: "Mithracidae",
    genus: "Maguimithrax",
    species: "M. spinosissimus",
    imageSrc:
      "//upload.wikimedia.org/wikipedia/commons/thumb/a/ad/Maguimithrax_spinosissimus_220213_a.jpg/220px-Maguimithrax_spinosissimus_220213_a.jpg",
  },
  "Mithraculus cinctimanus": {
    commonName: "Mithraculus cinctimanus",
    phylum: "Arthropoda",
    class: "Malacostraca",
    order: "Decapoda",
    family: "Majidae",
    genus: "Mithraculus",
    species: "M. cinctimanus",
    imageSrc: undefined,
  },
  "Panulirus argus": {
    commonName: "Panulirus argus",
    phylum: "Arthropoda",
    class: "Malacostraca",
    order: "Decapoda",
    family: "Palinuridae",
    genus: "Panulirus",
    species: "P. argus",
    imageSrc:
      "//upload.wikimedia.org/wikipedia/commons/thumb/e/ec/Panulirus_argus_NOAA.jpg/220px-Panulirus_argus_NOAA.jpg",
  },
  "Caribbean reef squid": {
    commonName: "Caribbean reef squid",
    phylum: "Mollusca",
    class: "Cephalopoda",
    order: "Myopsida",
    family: "Loliginidae",
    genus: "Sepioteuthis",
    species: "S. sepioidea",
    imageSrc:
      "//upload.wikimedia.org/wikipedia/commons/thumb/8/8f/Squid_colors_2.jpg/220px-Squid_colors_2.jpg",
  },
  "Caribbean reef octopus": {
    commonName: "Caribbean reef octopus",
    phylum: "Mollusca",
    class: "Cephalopoda",
    order: "Octopoda",
    family: "Octopodidae",
    genus: "Octopus",
    species: "O. briareus",
    imageSrc:
      "//upload.wikimedia.org/wikipedia/commons/thumb/c/cf/CaribbeanReefOctopus.jpg/220px-CaribbeanReefOctopus.jpg",
  },
  "Comb jellyfish": undefined,
  "Loggerhead sea turtle": {
    commonName: "Loggerhead sea turtle",
    phylum: "Chordata",
    class: "Reptilia",
    order: "Testudines",
    family: "Cheloniidae",
    genus: "CarettaRafinesque, 1814",
    species: "C. caretta",
    imageSrc:
      "//upload.wikimedia.org/wikipedia/commons/thumb/8/8e/Loggerhead_sea_turtle.jpg/220px-Loggerhead_sea_turtle.jpg",
  },
  "Aluterus schoepfii": {
    commonName: "Aluterus schoepfii",
    phylum: "Chordata",
    class: "Actinopterygii",
    order: "Tetraodontiformes",
    family: "Monacanthidae",
    genus: "Aluterus",
    species: "A. schoepfii",
    imageSrc:
      "//upload.wikimedia.org/wikipedia/commons/thumb/1/1e/Aluterus_schoepfii_SI.jpg/220px-Aluterus_schoepfii_SI.jpg",
  },
  "Stegastes leucostictus": {
    commonName: "Stegastes leucostictus",
    phylum: "Chordata",
    class: "Actinopterygii",
    order: "",
    family: "Pomacentridae",
    genus: "Stegastes",
    species: "S. leucostictus",
    imageSrc:
      "//upload.wikimedia.org/wikipedia/commons/thumb/8/8a/Stegastes_leucostictus.jpg/220px-Stegastes_leucostictus.jpg",
  },
  "Stegastes partitus": {
    commonName: "Stegastes partitus",
    phylum: "Chordata",
    class: "Actinopterygii",
    order: "",
    family: "Pomacentridae",
    genus: "Stegastes",
    species: "S. partitus",
    imageSrc:
      "//upload.wikimedia.org/wikipedia/commons/thumb/3/35/Stegastes_partitus_-_pone.0010676.g108.png/220px-Stegastes_partitus_-_pone.0010676.g108.png",
  },
  "Butter hamlet": {
    commonName: "Butter hamlet",
    phylum: "Chordata",
    class: "Actinopterygii",
    order: "Perciformes",
    family: "Serranidae",
    genus: "Hypoplectrus",
    species: "H. unicolor",
    imageSrc:
      "//upload.wikimedia.org/wikipedia/commons/thumb/f/f9/Butter_hamlet_fish.jpg/220px-Butter_hamlet_fish.jpg",
  },
  "Shy hamlet": {
    commonName: "Shy hamlet",
    phylum: "Chordata",
    class: "Actinopterygii",
    order: "Perciformes",
    family: "Serranidae",
    genus: "Hypoplectrus",
    species: "H. guttavarius",
    imageSrc:
      "//upload.wikimedia.org/wikipedia/commons/thumb/4/4d/Hypoplectrus_guttavarius_-_Wilhelma_01.jpg/220px-Hypoplectrus_guttavarius_-_Wilhelma_01.jpg",
  },
  "Indigo hamlet": {
    commonName: "Indigo hamlet",
    phylum: "Chordata",
    class: "Actinopterygii",
    order: "Perciformes",
    family: "Serranidae",
    genus: "Hypoplectrus",
    species: "H. indigo",
    imageSrc:
      "//upload.wikimedia.org/wikipedia/commons/thumb/8/80/Indigo_Hamlet.JPG/220px-Indigo_Hamlet.JPG",
  },
  Sunshinefish: {
    commonName: "Sunshinefish",
    phylum: "Chordata",
    class: "Actinopterygii",
    order: "",
    family: "Pomacentridae",
    genus: "Chromis",
    species: "C. insolata",
    imageSrc:
      "//upload.wikimedia.org/wikipedia/commons/thumb/4/4c/Chromis_insolata.jpg/220px-Chromis_insolata.jpg",
  },
  "Brown chromis": undefined,
  "Longsnout butterflyfish": {
    commonName: "Longsnout butterflyfish",
    phylum: undefined,
    class: undefined,
    order: undefined,
    family: undefined,
    genus: undefined,
    species: undefined,
    imageSrc: undefined,
  },
  "Spotfin butterflyfish": {
    commonName: "Spotfin butterflyfish",
    phylum: "Chordata",
    class: "Actinopterygii",
    order: "Perciformes",
    family: "Chaetodontidae",
    genus: "Chaetodon",
    species: "C. ocellatus",
    imageSrc:
      "//upload.wikimedia.org/wikipedia/commons/thumb/3/38/Spotfin_butterflyfish.jpg/220px-Spotfin_butterflyfish.jpg",
  },
  "Red hind": {
    commonName: "Red hind",
    phylum: "Chordata",
    class: "Actinopterygii",
    order: "Perciformes",
    family: "Serranidae",
    genus: "Epinephelus",
    species: "E. guttatus",
    imageSrc:
      "//upload.wikimedia.org/wikipedia/commons/thumb/1/11/Epinephelus_guttatus1.jpg/220px-Epinephelus_guttatus1.jpg",
  },
  "Harlequin bass": {
    commonName: "Harlequin bass",
    phylum: "Chordata",
    class: "Actinopterygii",
    order: "Perciformes",
    family: "Serranidae",
    genus: "Serranus",
    species: "S. tigrinus",
    imageSrc:
      "//upload.wikimedia.org/wikipedia/commons/thumb/3/30/Harlequin_Bass_%28Serranus_tigrinus%29.jpg/220px-Harlequin_Bass_%28Serranus_tigrinus%29.jpg",
  },
  Tobaccofish: undefined,
  "Acanthurus bahianus": {
    commonName: "Acanthurus bahianus",
    phylum: "Chordata",
    class: "Actinopterygii",
    order: "Acanthuriformes",
    family: "Acanthuridae",
    genus: "Acanthurus",
    species: "A. bahianus",
    imageSrc:
      "//upload.wikimedia.org/wikipedia/commons/thumb/7/76/Acanthurus_bahianus_SI3.jpg/220px-Acanthurus_bahianus_SI3.jpg",
  },
  "Green razorfish": {
    commonName: "Green razorfish",
    phylum: "Chordata",
    class: "Actinopterygii",
    order: "Labriformes",
    family: "Labridae",
    genus: "Xyrichtys",
    species: "X. splendens",
    imageSrc:
      "//upload.wikimedia.org/wikipedia/commons/thumb/1/15/Xyrichtys_splendens_1.jpg/220px-Xyrichtys_splendens_1.jpg",
  },
  "Pearly razorfish": {
    commonName: "Pearly razorfish",
    phylum: "Chordata",
    class: "Actinopterygii",
    order: "Labriformes",
    family: "Labridae",
    genus: "Xyrichtys",
    species: "X. novacula",
    imageSrc:
      "//upload.wikimedia.org/wikipedia/commons/thumb/c/c0/Labridae_-_Xyrichtys_novacula.JPG/220px-Labridae_-_Xyrichtys_novacula.JPG",
  },
  Porkfish: {
    commonName: "Porkfish",
    phylum: "Chordata",
    class: "Actinopterygii",
    order: "Perciformes",
    family: "Haemulidae",
    genus: "Anisotremus",
    species: "A. virginicus",
    imageSrc:
      "//upload.wikimedia.org/wikipedia/commons/thumb/a/ae/Anisotremus_virginicus_in_Madagascar_Reef.jpg/220px-Anisotremus_virginicus_in_Madagascar_Reef.jpg",
  },
  "Dog snapper": {
    commonName: "Dog snapper",
    phylum: "Chordata",
    class: "Actinopterygii",
    order: "Perciformes",
    family: "Lutjanidae",
    genus: "Lutjanus",
    species: "L. jocu",
    imageSrc:
      "//upload.wikimedia.org/wikipedia/commons/thumb/8/8f/Lutjanus_jocu_SI3.jpg/220px-Lutjanus_jocu_SI3.jpg",
  },
  "Cubera snapper": {
    commonName: "Cubera snapper",
    phylum: "Chordata",
    class: "Actinopterygii",
    order: "Perciformes",
    family: "Lutjanidae",
    genus: "Lutjanus",
    species: "L. cyanopterus",
    imageSrc:
      "//upload.wikimedia.org/wikipedia/commons/thumb/9/9f/Gfp-cubera-snapper.jpg/220px-Gfp-cubera-snapper.jpg",
  },
  "Mahogany snapper": undefined,
  "Green humphead parrotfish": {
    commonName: "Green humphead parrotfish",
    phylum: "Chordata",
    class: "Actinopterygii",
    order: "Labriformes",
    family: "Scaridae",
    genus: "BolbometoponJ. L. B. Smith, 1956",
    species: "B. muricatum",
    imageSrc:
      "//upload.wikimedia.org/wikipedia/commons/thumb/a/a0/Bumphead_parrotfish_%28Bolbometopon_muricatum%29_%2849509140173%29.jpg/220px-Bumphead_parrotfish_%28Bolbometopon_muricatum%29_%2849509140173%29.jpg",
  },
  "Sargassum triggerfish": {
    commonName: "Sargassum triggerfish",
    phylum: "Chordata",
    class: "Actinopterygii",
    order: "Tetraodontiformes",
    family: "Balistidae",
    genus: "Xanthichthys",
    species: "X. ringens",
    imageSrc:
      "//upload.wikimedia.org/wikipedia/commons/thumb/c/cb/Xanthichthys_ringens_-_pone.0010676.g191.png/220px-Xanthichthys_ringens_-_pone.0010676.g191.png",
  },
  "Honeycomb trunkfish": undefined,
  "Scrawled filefish": {
    commonName: "Scrawled filefish",
    phylum: "Chordata",
    class: "Actinopterygii",
    order: "Tetraodontiformes",
    family: "Monacanthidae",
    genus: "Aluterus",
    species: "A. scriptus",
    imageSrc:
      "//upload.wikimedia.org/wikipedia/commons/thumb/f/f4/Pez_lija_pintado_%28Aluterus_scriptus%29%2C_mar_Rojo%2C_Egipto%2C_2023-04-19%2C_DD_47.jpg/220px-Pez_lija_pintado_%28Aluterus_scriptus%29%2C_mar_Rojo%2C_Egipto%2C_2023-04-19%2C_DD_47.jpg",
  },
  "Longspine squirrelfish": {
    commonName: "Longspine squirrelfish",
    phylum: "Chordata",
    class: "Actinopterygii",
    order: "Holocentriformes",
    family: "Holocentridae",
    genus: "Holocentrus",
    species: "H. rufus",
    imageSrc:
      "//upload.wikimedia.org/wikipedia/commons/thumb/8/84/Holocentrus_rufus.jpg/220px-Holocentrus_rufus.jpg",
  },
  "Yellowhead jawfish": {
    commonName: "Yellowhead jawfish",
    phylum: "Chordata",
    class: "Actinopterygii",
    order: "",
    family: "Opistognathidae",
    genus: "Opistognathus",
    species: "O. aurifrons",
    imageSrc:
      "//upload.wikimedia.org/wikipedia/commons/thumb/d/d5/Opistognathus_aurifrons.jpg/220px-Opistognathus_aurifrons.jpg",
  },
  Balloonfish: {
    commonName: "Balloonfish",
    phylum: "Chordata",
    class: "Actinopterygii",
    order: "Tetraodontiformes",
    family: "TetraodontidaeBonaparte, 1832",
    genus: "",
    species: "",
    imageSrc:
      "//upload.wikimedia.org/wikipedia/commons/thumb/c/ce/Tetraodon-hispidus.jpg/220px-Tetraodon-hispidus.jpg",
  },
  "Jack-knifefish": {
    commonName: "Jack-knifefish",
    phylum: "Chordata",
    class: "Actinopterygii",
    order: "Acanthuriformes",
    family: "Sciaenidae",
    genus: "EquesBloch, 1793",
    species: "E. lanceolatus",
    imageSrc:
      "//upload.wikimedia.org/wikipedia/commons/thumb/c/c1/Equetus_lanceolatus_in_Madagascar_Reef.jpg/220px-Equetus_lanceolatus_in_Madagascar_Reef.jpg",
  },
  "Pareques acuminatus": {
    commonName: "Pareques acuminatus",
    phylum: "Chordata",
    class: "Actinopterygii",
    order: "Acanthuriformes",
    family: "Sciaenidae",
    genus: "Pareques",
    species: "P. acuminatus",
    imageSrc:
      "//upload.wikimedia.org/wikipedia/commons/thumb/d/de/Pareques_acuminatus.jpg/220px-Pareques_acuminatus.jpg",
  },
  Trumpetfish: {
    commonName: "Trumpetfish",
    phylum: "Chordata",
    class: "Actinopterygii",
    order: "Syngnathiformes",
    family: "AulostomidaeRafinesque, 1815[2]",
    genus: "AulostomusLacépède, 1803[1]",
    species: "",
    imageSrc:
      "//upload.wikimedia.org/wikipedia/commons/thumb/7/71/Aulostomus_chinensis_Maldives_2.JPG/220px-Aulostomus_chinensis_Maldives_2.JPG",
  },
  "Spotted goatfish": {
    commonName: "Spotted goatfish",
    phylum: "Chordata",
    class: "Actinopterygii",
    order: "Perciformes",
    family: "Mullidae",
    genus: "Pseudupeneus",
    species: "P. maculatus",
    imageSrc:
      "//upload.wikimedia.org/wikipedia/commons/thumb/b/bd/Pseudupeneus_maculatus_110864816.jpg/220px-Pseudupeneus_maculatus_110864816.jpg",
  },
  "Yellow goatfish": {
    commonName: "Yellow goatfish",
    phylum: "Chordata",
    class: "Actinopterygii",
    order: "Perciformes",
    family: "Mullidae",
    genus: "Mulloidichthys",
    species: "M. martinicus",
    imageSrc:
      "//upload.wikimedia.org/wikipedia/commons/thumb/4/4b/Mulloidichthys_martinicus_-_pone.0010676.g097.png/220px-Mulloidichthys_martinicus_-_pone.0010676.g097.png",
  },
  "Bermuda chub": {
    commonName: "Bermuda chub",
    phylum: "Chordata",
    class: "Actinopterygii",
    order: "Perciformes",
    family: "Kyphosidae",
    genus: "Kyphosus",
    species: "K. sectatrix",
    imageSrc:
      "//upload.wikimedia.org/wikipedia/commons/thumb/5/58/Kyphosus_sectatrix.jpg/220px-Kyphosus_sectatrix.jpg",
  },
  "Darkfin chub": undefined,
  "Bearded toadfish": undefined,
  "Channel flounder": undefined,
  "Eyed flounder": {
    commonName: "Eyed flounder",
    phylum: "Chordata",
    class: "Actinopterygii",
    order: "Pleuronectiformes",
    family: "Bothidae",
    genus: "Bothus",
    species: "B. ocellatus",
    imageSrc:
      "//upload.wikimedia.org/wikipedia/commons/thumb/c/cf/Bothus_ocellatus_de_Castelnau.jpg/220px-Bothus_ocellatus_de_Castelnau.jpg",
  },
  "Maculated flounder": undefined,
  "Brown garden eel": {
    commonName: "Brown garden eel",
    phylum: "Chordata",
    class: "Actinopterygii",
    order: "Anguilliformes",
    family: "Congridae",
    genus: "Heteroconger",
    species: "H. longissimus",
    imageSrc:
      "//upload.wikimedia.org/wikipedia/commons/thumb/0/05/Heteroconger_longissimus.jpg/220px-Heteroconger_longissimus.jpg",
  },
  "Caribbean blenny": {
    commonName: "Caribbean blenny",
    phylum: "Chordata",
    class: "Actinopterygii",
    order: "Blenniiformes",
    family: "Chaenopsidae",
    genus: "Emblemaria",
    species: "E. caldwelli",
    imageSrc:
      "//upload.wikimedia.org/wikipedia/commons/thumb/5/5a/Status_iucn3.1_LC.svg/220px-Status_iucn3.1_LC.svg.png",
  },
  "Flamingo tongue snail": {
    commonName: "Flamingo tongue snail",
    phylum: "Mollusca",
    class: "Gastropoda",
    order: "Littorinimorpha",
    family: "Ovulidae",
    genus: "Cyphoma",
    species: "C. gibbosum",
    imageSrc:
      "//upload.wikimedia.org/wikipedia/commons/thumb/d/d1/Cyphoma_gibbosum_%28living%29_2.jpg/220px-Cyphoma_gibbosum_%28living%29_2.jpg",
  },
  "Sand diver": {
    commonName: "Sand diver",
    phylum: undefined,
    class: undefined,
    order: undefined,
    family: undefined,
    genus: undefined,
    species: undefined,
    imageSrc: undefined,
  },
  "Red lizardfish": {
    commonName: "Red lizardfish",
    phylum: "Chordata",
    class: "Actinopterygii",
    order: "Aulopiformes",
    family: "Synodontidae",
    genus: "Synodus",
    species: "S. ulae",
    imageSrc:
      "//upload.wikimedia.org/wikipedia/commons/thumb/a/af/AkaES.jpg/220px-AkaES.jpg",
  },
  "Sheepshead porgy": {
    commonName: "Sheepshead porgy",
    phylum: "Chordata",
    class: "Actinopterygii",
    order: "Spariformes",
    family: "Sparidae",
    genus: "Calamus",
    species: "C. penna",
    imageSrc:
      "//upload.wikimedia.org/wikipedia/commons/thumb/e/ef/Sheepshead_porgy_-_Calamus_penna.jpg/220px-Sheepshead_porgy_-_Calamus_penna.jpg",
  },
  "Queen conch": {
    commonName: "Queen conch",
    phylum: "Mollusca",
    class: "Gastropoda",
    order: "Littorinimorpha",
    family: "Strombidae",
    genus: "Aliger",
    species: "A. gigas",
    imageSrc:
      "//upload.wikimedia.org/wikipedia/commons/thumb/b/b8/Lobatus_gigas_2.jpg/220px-Lobatus_gigas_2.jpg",
  },
  "Bearded fireworm": {
    commonName: "Bearded fireworm",
    phylum: "Annelida",
    class: "",
    order: "",
    family: "Amphinomidae",
    genus: "Hermodice",
    species: "H. carunculata",
    imageSrc:
      "//upload.wikimedia.org/wikipedia/commons/thumb/a/ae/Hermodice_carunculata_%28Bearded_Fireworm%29.jpg/220px-Hermodice_carunculata_%28Bearded_Fireworm%29.jpg",
  },
  "Christmas tree worm": {
    commonName: "Christmas tree worm",
    phylum: "Annelida",
    class: "",
    order: "Sabellida",
    family: "Serpulidae",
    genus: "Spirobranchus",
    species: "S. giganteus",
    imageSrc:
      "//upload.wikimedia.org/wikipedia/commons/thumb/e/ef/Spirobranchus_giganteus_%28Red_and_white_christmas_tree_worm%29.jpg/220px-Spirobranchus_giganteus_%28Red_and_white_christmas_tree_worm%29.jpg",
  },
  "Magnificent feather duster": undefined,
  "Brown fanworm": undefined,
  "Moon jelly": {
    commonName: "Moon jelly",
    phylum: "Cnidaria",
    class: "Scyphozoa",
    order: "Semaeostomeae",
    family: "Ulmaridae",
    genus: "AureliaLamarck, 1816",
    species: "",
    imageSrc:
      "//upload.wikimedia.org/wikipedia/commons/thumb/2/27/Moon_jellyfish_at_Gota_Sagher.JPG/220px-Moon_jellyfish_at_Gota_Sagher.JPG",
  },
  "Comb jelly": {
    commonName: "Comb jelly",
    phylum: "CtenophoraEschscholtz, 1829",
    class: "",
    order: "",
    family: "",
    genus: "",
    species: "",
    imageSrc:
      "//upload.wikimedia.org/wikipedia/commons/thumb/a/a8/Comb_jelly.jpg/220px-Comb_jelly.jpg",
  },
  "Thimble jelly": undefined,
  "Holothuria mexicana": {
    commonName: "Holothuria mexicana",
    phylum: "Echinodermata",
    class: "Holothuroidea",
    order: "Holothuriida",
    family: "Holothuriidae",
    genus: "Holothuria",
    species: "H. mexicana",
    imageSrc:
      "//upload.wikimedia.org/wikipedia/commons/thumb/4/48/Reef1075_-_Flickr_-_NOAA_Photo_Library.jpg/220px-Reef1075_-_Flickr_-_NOAA_Photo_Library.jpg",
  },
  "Channel clinging crab": undefined,
  "Nimble spray crab": {
    commonName: "Nimble spray crab",
    phylum: "Arthropoda",
    class: "Malacostraca",
    order: "Decapoda",
    family: "Percnidae",
    genus: "Percnon",
    species: "P. gibbesi",
    imageSrc:
      "//upload.wikimedia.org/wikipedia/commons/thumb/c/c8/Percnon_gibbesi_Linosa_053.jpg/220px-Percnon_gibbesi_Linosa_053.jpg",
  },
  "Hairy clinging crab": undefined,
  "Shortfinger neck crab": undefined,
  "Neck crab": undefined,
  "Reticulated brittle star": undefined,
  "Giant hermit crab": undefined,
  "Red reef hermit crab": undefined,
  "Banded coral shrimp": {
    commonName: "Banded coral shrimp",
    phylum: "Arthropoda",
    class: "Malacostraca",
    order: "Decapoda",
    family: "Stenopodidae",
    genus: "Stenopus",
    species: "S. hispidus",
    imageSrc:
      "//upload.wikimedia.org/wikipedia/commons/thumb/c/c3/Boxer_shrimp_at_Batu_Moncho.JPG/220px-Boxer_shrimp_at_Batu_Moncho.JPG",
  },
  "Spotted cleaner shrimp": {
    commonName: "Spotted cleaner shrimp",
    phylum: "Arthropoda",
    class: "Malacostraca",
    order: "Decapoda",
    family: "Palaemonidae",
    genus: "Periclimenes",
    species: "P. yucatanicus",
    imageSrc:
      "//upload.wikimedia.org/wikipedia/commons/thumb/6/69/Spotted_Cleaner_Shrimp_on_Giant_Anemone_by_Jessica_Rosenkrantz.jpg/220px-Spotted_Cleaner_Shrimp_on_Giant_Anemone_by_Jessica_Rosenkrantz.jpg",
  },
};

module.exports = { data };
