const data = {
  "Scrawled cowfish": {
    class: "Actinopterygii",
    order: "Tetraodontiformes",
    family: "Ostraciidae",
    genus: "Acanthostracion",
    species: "A. quadricornis",
    imageSrc:
      "//upload.wikimedia.org/wikipedia/commons/thumb/3/33/Scrawledcowfish.jpg/220px-Scrawledcowfish.jpg",
    commonName: "Scrawled cowfish",
  },
  "French angelfish": {
    class: "Actinopterygii",
    order: "Perciformes",
    family: "Pomacanthidae",
    genus: "Pomacanthus",
    species: "P. paru",
    imageSrc:
      "//upload.wikimedia.org/wikipedia/commons/thumb/d/d9/Pomacanthus_paru3.jpg/220px-Pomacanthus_paru3.jpg",
    commonName: "French angelfish",
  },
  "Grey angelfish": undefined,
  "Queen angelfish": {
    class: "Actinopterygii",
    order: "Perciformes",
    family: "Pomacanthidae",
    genus: "Holacanthus",
    species: "H. ciliaris",
    imageSrc:
      "//upload.wikimedia.org/wikipedia/commons/thumb/9/9f/Queen_Angelfish.jpg/220px-Queen_Angelfish.jpg",
    commonName: "Queen angelfish",
  },
  "Queen triggerfish": {
    class: "Actinopterygii",
    order: "Tetraodontiformes",
    family: "Balistidae",
    genus: "Balistes",
    species: "B. vetula",
    imageSrc:
      "//upload.wikimedia.org/wikipedia/commons/thumb/a/ae/4987_aquaimages.jpg/220px-4987_aquaimages.jpg",
    commonName: "Queen triggerfish",
  },
  "Banded butterflyfish": {
    class: "Actinopterygii",
    order: "Perciformes",
    family: "Chaetodontidae",
    genus: "Chaetodon",
    species: "C. striatus",
    imageSrc:
      "//upload.wikimedia.org/wikipedia/commons/thumb/6/65/Chaetodon_striatus_Brasil.jpg/220px-Chaetodon_striatus_Brasil.jpg",
    commonName: "Banded butterflyfish",
  },
  "Foureye butterflyfish": {
    class: "Actinopterygii",
    order: "Perciformes",
    family: "Chaetodontidae",
    genus: "Chaetodon",
    species: "C. capistratus",
    imageSrc:
      "//upload.wikimedia.org/wikipedia/commons/thumb/0/00/Chaetodon_capistratus1.jpg/220px-Chaetodon_capistratus1.jpg",
    commonName: "Foureye butterflyfish",
  },

  "Gray angelfish": {
    class: "Actinopterygii",
    order: "Perciformes",
    family: "Pomacanthidae",
    genus: "Pomacanthus",
    species: "P. arcuatus",
    imageSrc:
      "//upload.wikimedia.org/wikipedia/commons/thumb/d/d1/Pomacanthus_arcuatus_109580400.jpg/220px-Pomacanthus_arcuatus_109580400.jpg",
    commonName: "Gray angelfish",
  },
  "Blue tang": {
    class: undefined,
    order: undefined,
    family: undefined,
    genus: undefined,
    species: undefined,
    imageSrc: undefined,
    commonName: "Blue tang",
  },
  "Ocean surgeonfish": {
    class: undefined,
    order: undefined,
    family: undefined,
    genus: undefined,
    species: undefined,
    imageSrc: undefined,
    commonName: "Ocean surgeonfish",
  },
  "Queen parrotfish": {
    class: "Actinopterygii",
    order: "Labriformes",
    family: "Scaridae",
    genus: "Scarus",
    species: "S. vetula",
    imageSrc:
      "//upload.wikimedia.org/wikipedia/commons/thumb/1/17/Scarus_vetula.jpg/220px-Scarus_vetula.jpg",
    commonName: "Queen parrotfish",
  },
  "Striped parrotfish": undefined,
  "Stoplight parrotfish": {
    class: "Actinopterygii",
    order: "Labriformes",
    family: "Scaridae",
    genus: "Sparisoma",
    species: "S. viride",
    imageSrc:
      "//upload.wikimedia.org/wikipedia/commons/thumb/f/f3/Stoplight-parrotfish.jpg/220px-Stoplight-parrotfish.jpg",
    commonName: "Stoplight parrotfish",
  },
  "Princess parrotfish": {
    class: "Actinopterygii",
    order: "Labriformes",
    family: "Scaridae",
    genus: "Scarus",
    species: "S. taeniopterus",
    imageSrc:
      "//upload.wikimedia.org/wikipedia/commons/thumb/c/cb/Princess-parrotfish.png/220px-Princess-parrotfish.png",
    commonName: "Princess parrotfish",
  },
  "Tiger grouper": {
    class: "Actinopterygii",
    order: "Perciformes",
    family: "Serranidae",
    genus: "Mycteroperca",
    species: "M. tigris",
    imageSrc:
      "//upload.wikimedia.org/wikipedia/commons/thumb/1/10/Tiger_grouper.JPG/220px-Tiger_grouper.JPG",
    commonName: "Tiger grouper",
  },
  Coney: {
    class: undefined,
    order: undefined,
    family: undefined,
    genus: undefined,
    species: undefined,
    imageSrc: undefined,
    commonName: "Coney",
  },
  "French grunt": {
    class: "Actinopterygii",
    order: "Perciformes",
    family: "Haemulidae",
    genus: "Haemulon",
    species: "H. flavolineatum",
    imageSrc:
      "//upload.wikimedia.org/wikipedia/commons/thumb/3/3d/Haemulon_flavolineatum_French_grunt.jpg/220px-Haemulon_flavolineatum_French_grunt.jpg",
    commonName: "French grunt",
  },
  "Smallmouth grunt": undefined,
  "Bluestriped grunt": {
    class: "Actinopterygii",
    order: "Perciformes",
    family: "Haemulidae",
    genus: "Haemulon",
    species: "H. sciurus",
    imageSrc:
      "//upload.wikimedia.org/wikipedia/commons/thumb/5/54/Blue_Stripe_Grunt._Haemulon_sciurus.jpg/220px-Blue_Stripe_Grunt._Haemulon_sciurus.jpg",
    commonName: "Bluestriped grunt",
  },
  "Black margate": {
    class: "Actinopterygii",
    order: "Perciformes",
    family: "Haemulidae",
    genus: "Anisotremus",
    species: "A. surinamensis",
    imageSrc:
      "//upload.wikimedia.org/wikipedia/commons/thumb/a/a6/Anisotremus_surinamensis_1438594.jpg/220px-Anisotremus_surinamensis_1438594.jpg",
    commonName: "Black margate",
  },
  "Schoolmaster snapper": {
    class: "Actinopterygii",
    order: "Perciformes",
    family: "Lutjanidae",
    genus: "Lutjanus",
    species: "L. apodus",
    imageSrc:
      "//upload.wikimedia.org/wikipedia/commons/thumb/e/e8/Lutjanus.JPG/220px-Lutjanus.JPG",
    commonName: "Schoolmaster snapper",
  },
  "Yellowtail snapper": {
    class: "Actinopterygii",
    order: "Perciformes",
    family: "Lutjanidae",
    genus: "OcyurusT. N. Gill, 1862",
    species: "O. chrysurus",
    imageSrc:
      "//upload.wikimedia.org/wikipedia/commons/thumb/f/fe/Yellowtail_snapper_seen_from_Underwater_Tunnel_Atlantis.jpg/220px-Yellowtail_snapper_seen_from_Underwater_Tunnel_Atlantis.jpg",
    commonName: "Yellowtail snapper",
  },
  "Black durgon": {
    class: "Actinopterygii",
    order: "Tetraodontiformes",
    family: "Balistidae",
    genus: "Melichthys",
    species: "M. niger",
    imageSrc:
      "//upload.wikimedia.org/wikipedia/commons/thumb/3/33/Black_durgon_Melichthys_niger_%282414051345%29.jpg/220px-Black_durgon_Melichthys_niger_%282414051345%29.jpg",
    commonName: "Black durgon",
  },
  "Whitespotted filefish": {
    class: undefined,
    order: undefined,
    family: undefined,
    genus: undefined,
    species: undefined,
    imageSrc: undefined,
    commonName: "Whitespotted filefish",
  },
  Hogfish: {
    class: "Actinopterygii",
    order: "Labriformes",
    family: "Labridae",
    genus: "LachnolaimusG. Cuvier, 1829",
    species: "L. maximus",
    imageSrc:
      "//upload.wikimedia.org/wikipedia/commons/thumb/6/62/Hogfish.JPG/220px-Hogfish.JPG",
    commonName: "Hogfish",
  },
  "Spanish hogfish": {
    class: "Actinopterygii",
    order: "Labriformes",
    family: "Labridae",
    genus: "Bodianus",
    species: "B. rufus",
    imageSrc:
      "//upload.wikimedia.org/wikipedia/commons/thumb/6/65/Bodianus_rufus%2C_Adult_%28Spanish_Hogfish%29.jpg/220px-Bodianus_rufus%2C_Adult_%28Spanish_Hogfish%29.jpg",
    commonName: "Spanish hogfish",
  },

  "Green sea turtle": {
    commonName: "Green sea turtle",
    phylum: "Chordata",
    class: "Reptilia",
    order: "Testudines",
    family: "Cheloniidae",
    genus: "CheloniaBrongniart, 1800",
    species: "C. mydas",
    imageSrc:
      "//upload.wikimedia.org/wikipedia/commons/thumb/e/e5/Green_turtle_swimming_over_coral_reefs_in_Kona.jpg/220px-Green_turtle_swimming_over_coral_reefs_in_Kona.jpg",
  },
  "Hawksbill sea turtle": {
    commonName: "Hawksbill sea turtle",
    phylum: "Chordata",
    class: "Reptilia",
    order: "Testudines",
    family: "Cheloniidae",
    genus: "EretmochelysFitzinger, 1843",
    species: "E. imbricata",
    imageSrc:
      "//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Eretmochelys-imbricata-K%C3%A9lonia-2.JPG/220px-Eretmochelys-imbricata-K%C3%A9lonia-2.JPG",
  },
  Bluehead: {
    commonName: "Bluehead",
    phylum: "Chordata",
    class: "Actinopterygii",
    order: "Labriformes",
    family: "Labridae",
    genus: "Thalassoma",
    species: "T. amblycephalum",
    imageSrc:
      "//upload.wikimedia.org/wikipedia/commons/thumb/4/40/KogashiraBRnup.jpg/220px-KogashiraBRnup.jpg",
  },
  "Yellowhead wrasse": {
    commonName: "Yellowhead wrasse",
    phylum: "Chordata",
    class: "Actinopterygii",
    order: "Labriformes",
    family: "Labridae",
    genus: "Halichoeres",
    species: "H. garnoti",
    imageSrc:
      "//upload.wikimedia.org/wikipedia/commons/thumb/2/25/Reef1538_-_Flickr_-_NOAA_Photo_Library.jpg/220px-Reef1538_-_Flickr_-_NOAA_Photo_Library.jpg",
  },
  "Clown wrasse": {
    commonName: "Clown wrasse",
    phylum: undefined,
    class: undefined,
    order: undefined,
    family: undefined,
    genus: undefined,
    species: undefined,
    imageSrc: undefined,
  },
  "Rainbow wrasse": {
    commonName: "Rainbow wrasse",
    phylum: "Chordata",
    class: "Actinopterygii",
    order: "Labriformes",
    family: "Labridae",
    genus: "CorisLacépède, 1801",
    species: "",
    imageSrc:
      "//upload.wikimedia.org/wikipedia/commons/thumb/e/eb/Coris_gaimard_real.jpg/220px-Coris_gaimard_real.jpg",
  },
  "Yellowcheek wrasse": {
    commonName: "Yellowcheek wrasse",
    phylum: "Chordata",
    class: "Actinopterygii",
    order: "Labriformes",
    family: "Labridae",
    genus: "Halichoeres",
    species: "H. cyanocephalus",
    imageSrc:
      "//upload.wikimedia.org/wikipedia/commons/thumb/9/9c/Halichoeres_cyanocephalus.jpg/220px-Halichoeres_cyanocephalus.jpg",
  },
  "Greenband wrasse": undefined,
  "Painted wrasse": undefined,
  "Midnight parrotfish": {
    commonName: "Midnight parrotfish",
    phylum: "Chordata",
    class: "Actinopterygii",
    order: "Labriformes",
    family: "Scaridae",
    genus: "Scarus",
    species: "S. coelestinus",
    imageSrc:
      "//upload.wikimedia.org/wikipedia/commons/thumb/3/3c/Midnight-parrotfish.png/220px-Midnight-parrotfish.png",
  },
  "Blue parrotfish": {
    commonName: "Blue parrotfish",
    phylum: "Chordata",
    class: "Actinopterygii",
    order: "Labriformes",
    family: "Scaridae",
    genus: "Scarus",
    species: "S. coeruleus",
    imageSrc:
      "//upload.wikimedia.org/wikipedia/commons/thumb/b/b2/Scarus_coeruleus_in_Madagascar_Reef.jpg/220px-Scarus_coeruleus_in_Madagascar_Reef.jpg",
  },
  "Rainbow parrotfish": {
    commonName: "Rainbow parrotfish",
    phylum: "Chordata",
    class: "Actinopterygii",
    order: "Labriformes",
    family: "Scaridae",
    genus: "Scarus",
    species: "S. guacamaia",
    imageSrc:
      "//upload.wikimedia.org/wikipedia/commons/thumb/f/f7/Rainbow_parrotfish.jpg/220px-Rainbow_parrotfish.jpg",
  },
  "Redtail parrotfish": {
    commonName: "Redtail parrotfish",
    phylum: "Chordata",
    class: "Actinopterygii",
    order: "Labriformes",
    family: "Scaridae",
    genus: "Sparisoma",
    species: "S. chrysopterum",
    imageSrc:
      "//upload.wikimedia.org/wikipedia/commons/thumb/5/51/Sparisoma_chrysopterum_-_pone.0010676.g135.png/220px-Sparisoma_chrysopterum_-_pone.0010676.g135.png",
  },
  "Yellowhead jawfish": {
    commonName: "Yellowhead jawfish",
    phylum: "Chordata",
    class: "Actinopterygii",
    order: "",
    family: "Opistognathidae",
    genus: "Opistognathus",
    species: "O. aurifrons",
    imageSrc:
      "//upload.wikimedia.org/wikipedia/commons/thumb/d/d5/Opistognathus_aurifrons.jpg/220px-Opistognathus_aurifrons.jpg",
  },
  "Banded jawfish": undefined,
  "Great barracuda": {
    commonName: "Great barracuda",
    phylum: "Chordata",
    class: "Actinopterygii",
    order: "Istiophoriformes",
    family: "Sphyraenidae",
    genus: "Sphyraena",
    species: "S. barracuda",
    imageSrc:
      "//upload.wikimedia.org/wikipedia/commons/thumb/e/eb/Barracuda_laban.jpg/220px-Barracuda_laban.jpg",
  },
  "Palehead blenny": {
    commonName: "Palehead blenny",
    phylum: "Chordata",
    class: "Actinopterygii",
    order: "Blenniiformes",
    family: "Labrisomidae",
    genus: "Gobioclinus",
    species: "G. gobio",
    imageSrc:
      "//upload.wikimedia.org/wikipedia/commons/thumb/9/9d/Labrisomus_gobio_-_pone.0010676.g145.png/220px-Labrisomus_gobio_-_pone.0010676.g145.png",
  },
  "Blue gobi": undefined,
  "Yellowtail damselfish": {
    commonName: "Yellowtail damselfish",
    phylum: "Chordata",
    class: "Actinopterygii",
    order: "",
    family: "Pomacentridae",
    genus: "Microspathodon",
    species: "M. chrysurus",
    imageSrc:
      "//upload.wikimedia.org/wikipedia/commons/thumb/c/c7/Yellotaildamsel.jpg/220px-Yellotaildamsel.jpg",
  },
  Surgeonfish: {
    commonName: "Surgeonfish",
    phylum: "Chordata",
    class: "Actinopterygii",
    order: "Acanthuriformes",
    family: "AcanthuridaeBonaparte, 1835[1]",
    genus: "",
    species: "",
    imageSrc:
      "//upload.wikimedia.org/wikipedia/commons/thumb/f/f6/Acanthurussohal-ArabischerDoktor.jpg/220px-Acanthurussohal-ArabischerDoktor.jpg",
  },
  "Blue chromis": {
    commonName: "Blue chromis",
    phylum: "Chordata",
    class: "Actinopterygii",
    order: "",
    family: "Pomacentridae",
    genus: "Chromis",
    species: "C. cyanea",
    imageSrc:
      "//upload.wikimedia.org/wikipedia/commons/thumb/e/e4/Chromis_cyanea_Gratwicke.jpg/220px-Chromis_cyanea_Gratwicke.jpg",
  },
  "Rock beauty": {
    commonName: "Rock beauty",
    phylum: "Chordata",
    class: "Actinopterygii",
    order: "Perciformes",
    family: "Pomacanthidae",
    genus: "Holacanthus",
    species: "H. tricolor",
    imageSrc:
      "//upload.wikimedia.org/wikipedia/commons/thumb/a/a2/Holacanthus_tricolor_1.jpg/220px-Holacanthus_tricolor_1.jpg",
  },
  "Blue angelfish": {
    commonName: "Blue angelfish",
    phylum: "Chordata",
    class: "Actinopterygii",
    order: "Perciformes",
    family: "Pomacanthidae",
    genus: "Holacanthus",
    species: "H. bermudensis",
    imageSrc:
      "//upload.wikimedia.org/wikipedia/commons/thumb/a/a0/Blue_Angelfish_JG.jpg/220px-Blue_Angelfish_JG.jpg",
  },
  "Reef butterflyfish": {
    commonName: "Reef butterflyfish",
    phylum: "Chordata",
    class: "Actinopterygii",
    order: "Perciformes",
    family: "Chaetodontidae",
    genus: "Chaetodon",
    species: "C. sedentarius",
    imageSrc:
      "//upload.wikimedia.org/wikipedia/commons/thumb/9/9a/Chaetodon_sedentarius_Brasil.jpg/220px-Chaetodon_sedentarius_Brasil.jpg",
  },
  "Threeband butterflyfish": undefined,
  "Spotted drum": {
    commonName: "Spotted drum",
    phylum: "Chordata",
    class: "Actinopterygii",
    order: "Acanthuriformes",
    family: "Sciaenidae",
    genus: "Eques",
    species: "E. punctatus",
    imageSrc:
      "//upload.wikimedia.org/wikipedia/commons/thumb/e/ee/Spotted-drum.png/220px-Spotted-drum.png",
  },
  "White grunt": {
    commonName: "White grunt",
    phylum: "Chordata",
    class: "Actinopterygii",
    order: "Perciformes",
    family: "Haemulidae",
    genus: "Haemulon",
    species: "H. plumierii",
    imageSrc:
      "//upload.wikimedia.org/wikipedia/commons/thumb/5/58/White_Grunt_%285658507044%29.jpg/220px-White_Grunt_%285658507044%29.jpg",
  },
  Sheepshead: {
    commonName: "Sheepshead",
    phylum: undefined,
    class: undefined,
    order: undefined,
    family: undefined,
    genus: undefined,
    species: undefined,
    imageSrc: undefined,
  },
  "Mutton snapper": {
    commonName: "Mutton snapper",
    phylum: "Chordata",
    class: "Actinopterygii",
    order: "Perciformes",
    family: "Lutjanidae",
    genus: "Lutjanus",
    species: "L. analis",
    imageSrc:
      "//upload.wikimedia.org/wikipedia/commons/thumb/1/1d/Lutjanus_analis_SI.jpg/220px-Lutjanus_analis_SI.jpg",
  },
  "Yellowtail snapper": {
    commonName: "Yellowtail snapper",
    phylum: "Chordata",
    class: "Actinopterygii",
    order: "Perciformes",
    family: "Lutjanidae",
    genus: "OcyurusT. N. Gill, 1862",
    species: "O. chrysurus",
    imageSrc:
      "//upload.wikimedia.org/wikipedia/commons/thumb/f/fe/Yellowtail_snapper_seen_from_Underwater_Tunnel_Atlantis.jpg/220px-Yellowtail_snapper_seen_from_Underwater_Tunnel_Atlantis.jpg",
  },
  "Bar Jack": {
    commonName: "Bar Jack",
    phylum: "Chordata",
    class: "Actinopterygii",
    order: "Carangiformes",
    family: "Carangidae",
    genus: "Caranx",
    species: "C. ruber",
    imageSrc:
      "//upload.wikimedia.org/wikipedia/commons/thumb/2/23/Bar_jack_portrait.jpg/220px-Bar_jack_portrait.jpg",
  },
  Palometa: {
    commonName: "Palometa",
    phylum: undefined,
    class: undefined,
    order: undefined,
    family: undefined,
    genus: undefined,
    species: undefined,
    imageSrc: undefined,
  },
  "Bigeye scad": {
    commonName: "Bigeye scad",
    phylum: "Chordata",
    class: "Actinopterygii",
    order: "Carangiformes",
    family: "Carangidae",
    genus: "Selar",
    species: "S. crumenophthalmus",
    imageSrc:
      "//upload.wikimedia.org/wikipedia/commons/thumb/4/4d/Fish4443_-_Flickr_-_NOAA_Photo_Library.jpg/220px-Fish4443_-_Flickr_-_NOAA_Photo_Library.jpg",
  },
  "Glasseye snapper": {
    commonName: "Glasseye snapper",
    phylum: "Chordata",
    class: "Actinopterygii",
    order: "Perciformes",
    family: "Priacanthidae",
    genus: "HeteropriacanthusFitch & Crooke, 1984",
    species: "H. cruentatus",
    imageSrc:
      "//upload.wikimedia.org/wikipedia/commons/thumb/7/70/Priacanthus_cruentatus.jpg/220px-Priacanthus_cruentatus.jpg",
  },
  "Pale cardinalfish": undefined,
  "Fairy basslet": {
    commonName: "Fairy basslet",
    phylum: "Chordata",
    class: "Actinopterygii",
    order: "Perciformes",
    family: "SerranidaeSwainson, 1839[1]",
    genus: "",
    species: "",
    imageSrc:
      "//upload.wikimedia.org/wikipedia/commons/thumb/c/c8/Cromileptes_altivelis_-_Paddelbarsch_-_Panther_grouper.jpg/220px-Cromileptes_altivelis_-_Paddelbarsch_-_Panther_grouper.jpg",
  },
  "Blackcap basslet": {
    commonName: "Blackcap basslet",
    phylum: "Chordata",
    class: "Actinopterygii",
    order: "",
    family: "Grammatidae",
    genus: "Gramma",
    species: "G. melacara",
    imageSrc:
      "//upload.wikimedia.org/wikipedia/commons/thumb/0/07/Black_Cap_Basslet.jpg/220px-Black_Cap_Basslet.jpg",
  },
  "Mutton hamlet": {
    commonName: "Mutton hamlet",
    phylum: "Chordata",
    class: "Actinopterygii",
    order: "Perciformes",
    family: "Serranidae",
    genus: "Dermatolepis",
    species: "D. inermis",
    imageSrc:
      "//upload.wikimedia.org/wikipedia/commons/thumb/b/b7/Sanc0498_-_Flickr_-_NOAA_Photo_Library.jpg/220px-Sanc0498_-_Flickr_-_NOAA_Photo_Library.jpg",
  },
  "Black grouper": {
    commonName: "Black grouper",
    phylum: "Chordata",
    class: "Actinopterygii",
    order: "Perciformes",
    family: "Serranidae",
    genus: "Mycteroperca",
    species: "M. bonaci",
    imageSrc:
      "//upload.wikimedia.org/wikipedia/commons/thumb/1/1f/Black_grouper2.jpg/220px-Black_grouper2.jpg",
  },
  "Reef bass": undefined,
  "Sand perch": {
    commonName: "Sand perch",
    phylum: "Chordata",
    class: "Actinopterygii",
    order: "Trachiniformes",
    family: "PinguipedidaeGünther, 1860",
    genus: "",
    species: "",
    imageSrc:
      "//upload.wikimedia.org/wikipedia/commons/thumb/5/53/Parapercis_hexophtalma_1.jpg/220px-Parapercis_hexophtalma_1.jpg",
  },
  "Nassau grouper": {
    commonName: "Nassau grouper",
    phylum: "Chordata",
    class: "Actinopterygii",
    order: "Perciformes",
    family: "Serranidae",
    genus: "Epinephelus",
    species: "E. striatus",
    imageSrc:
      "//upload.wikimedia.org/wikipedia/commons/thumb/8/8e/2017%2C_cuba%2C_jardines_aggressor%2C_los_indios%2C_nassau_grouper_maw_%2836883128693%29.jpg/220px-2017%2C_cuba%2C_jardines_aggressor%2C_los_indios%2C_nassau_grouper_maw_%2836883128693%29.jpg",
  },
  "Lined seahorse": {
    commonName: "Lined seahorse",
    phylum: "Chordata",
    class: "Actinopterygii",
    order: "Syngnathiformes",
    family: "Syngnathidae",
    genus: "Hippocampus",
    species: "H. erectus",
    imageSrc:
      "//upload.wikimedia.org/wikipedia/commons/thumb/b/bf/Lined_Seahorse-_Hippocampus_erectus_%286042886100%29.jpg/220px-Lined_Seahorse-_Hippocampus_erectus_%286042886100%29.jpg",
  },
  "Spotted scorpionfish": {
    commonName: "Spotted scorpionfish",
    phylum: "Chordata",
    class: "Actinopterygii",
    order: "Scorpaeniformes",
    family: "Scorpaenidae",
    genus: "Scorpaena",
    species: "S. guttata",
    imageSrc:
      "//upload.wikimedia.org/wikipedia/commons/thumb/c/c4/Scorpaena_guttata.jpg/220px-Scorpaena_guttata.jpg",
  },
  "Reef scorpionfish": undefined,
  Lionfish: {
    commonName: "Lionfish",
    phylum: "Chordata",
    class: "Actinopterygii",
    order: "Scorpaeniformes",
    family: "Scorpaenidae",
    genus: "PteroisOken, 1817[1]",
    species: "",
    imageSrc:
      "//upload.wikimedia.org/wikipedia/commons/thumb/3/3d/Red_lionfish_near_Gilli_Banta_Island.JPG/220px-Red_lionfish_near_Gilli_Banta_Island.JPG",
  },
  "Reef squirrelfish": {
    commonName: "Reef squirrelfish",
    phylum: "Chordata",
    class: "Actinopterygii",
    order: "Holocentriformes",
    family: "Holocentridae",
    genus: "Sargocentron",
    species: "S. coruscum",
    imageSrc:
      "//upload.wikimedia.org/wikipedia/commons/thumb/e/e6/Sargocentron_coruscum_-_pone.0010676.g039.png/220px-Sargocentron_coruscum_-_pone.0010676.g039.png",
  },
  "Coral toadfish": {
    commonName: "Coral toadfish",
    phylum: "Chordata",
    class: "Actinopterygii",
    order: "Batrachoidiformes",
    family: "Batrachoididae",
    genus: "Sanopus",
    species: "S. splendidus",
    imageSrc:
      "//upload.wikimedia.org/wikipedia/commons/thumb/2/2c/Splendidtoadfish_laban.jpg/220px-Splendidtoadfish_laban.jpg",
  },
  "Dwarf frogfish": {
    commonName: "Dwarf frogfish",
    phylum: "Chordata",
    class: "Actinopterygii",
    order: "Lophiiformes",
    family: "Antennariidae",
    genus: "Antennarius",
    species: "A. pauciradiatus",
    imageSrc:
      "//upload.wikimedia.org/wikipedia/commons/thumb/5/56/Antennarius_pauciradiatus_-_pone.0010676.g028.png/220px-Antennarius_pauciradiatus_-_pone.0010676.g028.png",
  },
  Tarpon: {
    commonName: "Tarpon",
    phylum: "Chordata",
    class: "Actinopterygii",
    order: "Elopiformes",
    family: "MegalopidaeD. S. Jordan, 1923",
    genus: "MegalopsValenciennes, 1847",
    species: "",
    imageSrc:
      "//upload.wikimedia.org/wikipedia/commons/thumb/7/7e/Atlantic_tarpon.jpg/220px-Atlantic_tarpon.jpg",
  },
  "Green moray eel": {
    commonName: "Green moray eel",
    phylum: "Chordata",
    class: "Actinopterygii",
    order: "Anguilliformes",
    family: "Muraenidae",
    genus: "Gymnothorax",
    species: "G. funebris",
    imageSrc:
      "//upload.wikimedia.org/wikipedia/commons/thumb/3/33/GreenMorayEel.JPG/220px-GreenMorayEel.JPG",
  },
  "Spotted moray eel": {
    commonName: "Spotted moray eel",
    phylum: "Chordata",
    class: "Actinopterygii",
    order: "Anguilliformes",
    family: "Muraenidae",
    genus: "Gymnothorax",
    species: "G. isingteena",
    imageSrc:
      "//upload.wikimedia.org/wikipedia/commons/thumb/7/74/Gymnothorax_isingteena.jpg/220px-Gymnothorax_isingteena.jpg",
  },
  "Purplemouth moral eel": undefined,
  "Goldentail moral eey": undefined,
  "Spotted eagle ray": {
    commonName: "Spotted eagle ray",
    phylum: "Chordata",
    class: "Chondrichthyes",
    order: "Myliobatiformes",
    family: "Aetobatidae",
    genus: "Aetobatus",
    species: "A. narinari",
    imageSrc:
      "//upload.wikimedia.org/wikipedia/commons/thumb/a/ad/Eagle_Ray_Turks_and_Caicos_Dec_15_2006.JPG/220px-Eagle_Ray_Turks_and_Caicos_Dec_15_2006.JPG",
  },
  "Southern stingray": {
    commonName: "Southern stingray",
    phylum: "Chordata",
    class: "Chondrichthyes",
    order: "Myliobatiformes",
    family: "Dasyatidae",
    genus: "Hypanus",
    species: "H. americanus",
    imageSrc:
      "//upload.wikimedia.org/wikipedia/commons/thumb/2/29/Dasyatis_americana_SI.jpg/220px-Dasyatis_americana_SI.jpg",
  },
  "Yellow stingray": {
    commonName: "Yellow stingray",
    phylum: "Chordata",
    class: "Chondrichthyes",
    order: "Myliobatiformes",
    family: "Urotrygonidae",
    genus: "Urobatis",
    species: "U. jamaicensis",
    imageSrc:
      "//upload.wikimedia.org/wikipedia/commons/thumb/5/53/Yellow_Stingray%2C_Belize%2C_2007-09.jpg/220px-Yellow_Stingray%2C_Belize%2C_2007-09.jpg",
  },
  "Lesser electric ray": {
    commonName: "Lesser electric ray",
    phylum: "Chordata",
    class: "Chondrichthyes",
    order: "Torpediniformes",
    family: "Narcinidae",
    genus: "Narcine",
    species: "N. bancroftii",
    imageSrc:
      "//upload.wikimedia.org/wikipedia/commons/thumb/b/b7/Fish4345_-_Flickr_-_NOAA_Photo_Library.jpg/220px-Fish4345_-_Flickr_-_NOAA_Photo_Library.jpg",
  },
  Guitarfish: {
    commonName: "Guitarfish",
    phylum: "Chordata",
    class: "Chondrichthyes",
    order: "Rhinopristiformes",
    family: "RhinobatidaeJ. P. Müller & Henle, 1837",
    genus: "",
    species: "",
    imageSrc:
      "//upload.wikimedia.org/wikipedia/commons/thumb/f/fa/Shovelnose_guitarfish.JPG/220px-Shovelnose_guitarfish.JPG",
  },
  "Manta ray": {
    commonName: "Manta ray",
    phylum: "Chordata",
    class: "Chondrichthyes",
    order: "Myliobatiformes",
    family: "Mobulidae",
    genus: "MantaBancroft, 1829[2]",
    species: "",
    imageSrc:
      "//upload.wikimedia.org/wikipedia/commons/thumb/3/30/Dharavandhoo_Thila_-_Manata_Black_Pearl.JPG/220px-Dharavandhoo_Thila_-_Manata_Black_Pearl.JPG",
  },
  "Nurse shark": {
    commonName: "Nurse shark",
    phylum: "Chordata",
    class: "Chondrichthyes",
    order: "Orectolobiformes",
    family: "Ginglymostomatidae",
    genus: "Ginglymostoma",
    species: "G. cirratum",
    imageSrc:
      "//upload.wikimedia.org/wikipedia/commons/thumb/d/d1/Nurse_shark.jpg/220px-Nurse_shark.jpg",
  },
  "Whitespotted puffer": undefined,
  "Spotted trunkfish": {
    commonName: "Spotted trunkfish",
    phylum: "Chordata",
    class: "Actinopterygii",
    order: "Tetraodontiformes",
    family: "Ostraciidae",
    genus: "Lactophrys",
    species: "L. bicaudalis",
    imageSrc:
      "//upload.wikimedia.org/wikipedia/commons/thumb/f/fb/Spotted_Trunkfish.jpg/220px-Spotted_Trunkfish.jpg",
  },
  "Yellow boxfish": {
    commonName: "Yellow boxfish",
    phylum: "Chordata",
    class: "Actinopterygii",
    order: "Tetraodontiformes",
    family: "Ostraciidae",
    genus: "Ostracion",
    species: "O. cubicum",
    imageSrc:
      "//upload.wikimedia.org/wikipedia/commons/thumb/7/79/Kofferfisch_%28Ostracion_cubicus%29_02.jpg/220px-Kofferfisch_%28Ostracion_cubicus%29_02.jpg",
  },
  "Whitespotted pygmy filefish": {
    commonName: "Whitespotted pygmy filefish",
    phylum: "Chordata",
    class: "Actinopterygii",
    order: "Tetraodontiformes",
    family: "Monacanthidae",
    genus: "Rudarius",
    species: "R. ercodes",
    imageSrc:
      "//upload.wikimedia.org/wikipedia/commons/thumb/d/d8/AmimeHGoya.jpg/220px-AmimeHGoya.jpg",
  },
  "Broom filefish": {
    commonName: "Broom filefish",
    phylum: "Chordata",
    class: "Actinopterygii",
    order: "Tetraodontiformes",
    family: "Monacanthidae",
    genus: "AmansesJ. E. Gray, 1835",
    species: "A. scopas",
    imageSrc:
      "//upload.wikimedia.org/wikipedia/commons/thumb/1/1e/Amanses_scopas.jpg/220px-Amanses_scopas.jpg",
  },
  "Peacock flounder": {
    commonName: "Peacock flounder",
    phylum: "Chordata",
    class: "Actinopterygii",
    order: "Pleuronectiformes",
    family: "Bothidae",
    genus: "Bothus",
    species: "B. mancus",
    imageSrc:
      "//upload.wikimedia.org/wikipedia/commons/thumb/9/96/Bothidae_-_Bothus_mancus.jpg/220px-Bothidae_-_Bothus_mancus.jpg",
  },
  "Black durgon": {
    commonName: "Black durgon",
    phylum: "Chordata",
    class: "Actinopterygii",
    order: "Tetraodontiformes",
    family: "Balistidae",
    genus: "Melichthys",
    species: "M. niger",
    imageSrc:
      "//upload.wikimedia.org/wikipedia/commons/thumb/3/33/Black_durgon_Melichthys_niger_%282414051345%29.jpg/220px-Black_durgon_Melichthys_niger_%282414051345%29.jpg",
  },
};

module.exports = { data };
